use sales_analytics;

CREATE TABLE sales (
    order_id INT PRIMARY KEY,
    customer_name VARCHAR(100),
    city VARCHAR(50),
    product VARCHAR(100),
    category VARCHAR(50),
    quantity INT,
    price DECIMAL(10,2),
    order_date DATE
);
 
INSERT INTO sales
(order_id, customer_name, city, product, category, quantity, price, order_date)
VALUES
(101,'Dhruv','Delhi','Laptop','Electronics',1,65000,'2025-01-05'),
(102,'Amit','Mumbai','Mobile','Electronics',2,25000,'2025-01-08'),
(103,'Priya','Delhi','Headphones','Electronics',3,2000,'2025-01-12'),
(104,'Rahul','Bangalore','Chair','Furniture',4,3500,'2025-01-15'),
(105,'Sneha','Pune','Table','Furniture',1,8500,'2025-01-18'),
(106,'Ankit','Delhi','Laptop','Electronics',1,70000,'2025-02-02'),
(107,'Neha','Mumbai','Monitor','Electronics',2,15000,'2025-02-06'),
(108,'Riya','Pune','Chair','Furniture',6,3200,'2025-02-09'),
(109,'Vikas','Jaipur','Mobile','Electronics',1,28000,'2025-02-15'),
(110,'Karan','Delhi','Keyboard','Accessories',5,1200,'2025-02-18'),
(111,'Amit','Mumbai','Mouse','Accessories',8,700,'2025-03-02'),
(112,'Priya','Delhi','Laptop','Electronics',1,68000,'2025-03-06'),
(113,'Rahul','Bangalore','Desk','Furniture',2,12000,'2025-03-10'),
(114,'Sneha','Pune','Tablet','Electronics',2,18000,'2025-03-14'),
(115,'Dhruv','Delhi','Mobile','Electronics',1,30000,'2025-03-20'),
(116,'Neha','Mumbai','Chair','Furniture',3,3400,'2025-04-01'),
(117,'Ankit','Delhi','Monitor','Electronics',1,16000,'2025-04-05'),
(118,'Riya','Pune','Mouse','Accessories',10,650,'2025-04-09'),
(119,'Vikas','Jaipur','Keyboard','Accessories',6,1300,'2025-04-14'),
(120,'Karan','Delhi','Desk','Furniture',1,15000,'2025-04-18'),
(121,'Amit','Mumbai','Laptop','Electronics',1,72000,'2025-05-03'),
(122,'Priya','Delhi','Mobile','Electronics',2,29000,'2025-05-07'),
(123,'Rahul','Bangalore','Table','Furniture',2,9000,'2025-05-12'),
(124,'Sneha','Pune','Keyboard','Accessories',4,1100,'2025-05-18'),
(125,'Dhruv','Delhi','Headphones','Electronics',5,2500,'2025-05-22'),
(126,'Neha','Mumbai','Laptop','Electronics',1,69000,'2025-06-01'),
(127,'Ankit','Delhi','Chair','Furniture',2,3600,'2025-06-05'),
(128,'Riya','Pune','Monitor','Electronics',1,17000,'2025-06-10'),
(129,'Vikas','Jaipur','Tablet','Electronics',2,19000,'2025-06-14'),
(130,'Karan','Delhi','Mouse','Accessories',7,750,'2025-06-20');


select * from sales;

-- Count total orders from each city. -- 

SELECT city , COUNT(order_id) AS total_orders 
FROM sales GROUP BY city;

-- Find total revenue generated by each city. -- 
SELECT city , SUM(price * quantity) AS total_revenue 
FROM sales GROUP BY city;

-- Find average order value for every city. -- 
SELECT city , AVG(quantity * price) AS avg_order_value
FROM sales GROUP BY city ;

-- Show total quantity sold for each product. -- 
SELECT product , SUM(quantity) AS total_quantity
FROM sales GROUP BY product;

-- Find maximum price of each product. -- 
SELECT product , MAX(price) AS maximum_price
FROM sales GROUP BY product;

-- Find minimum price for each category. -- 
SELECT category , MIN(price) AS minimum_price
FROM sales GROUP BY category;

-- Find average quantity ordered for each product. -- 
SELECT product , AVG(quantity) AS average_quantity 
FROM sales GROUP BY product;

-- Show total revenue for every category. -- 
SELECT category , SUM(price * quantity) AS total_revenue
FROM sales GROUP  BY category;

-- Count unique customers in each city.--
SELECT city , COUNT(DISTINCT customer_name) AS unique_customer
FROM sales GROUP BY city;


-- Find the customer who placed the highest number of orders. -- 
SELECT customer_name , COUNT(order_id) AS total_orders
FROM sales GROUP BY customer_name
ORDER BY total_orders DESC
LIMIT 1;

-- Find total monthly revenue. -- 
SELECT MONTHNAME(order_date) , SUM(price * quantity ) AS monthly_revenue
FROM sales GROUP BY MONTHNAME(order_date);

-- Find the highest revenue city. -- 
SELECT MONTHNAME(order_date) , SUM(price * quantity ) AS monthly_revenue
FROM sales 
GROUP BY MONTHNAME(order_date)
ORDER BY monthly_revenue DESC
LIMIT 1;

-- Find the most ordered product. --
SELECT product , COUNT(quantity) FROM sales 
GROUP BY product
ORDER BY COUNT(quantity) DESC
LIMIT 1;

-- Find top 3 customers based on total purchase amount.
SELECT customer_name , SUM(quantity * price) AS purchase_amount
FROM sales
GROUP BY customer_name
ORDER BY purchase_amount DESC 
LIMIT 3;

-- Find cities having more than 100 orders. -- 
SELECT city , COUNT(order_id) AS total_orders 
FROM sales 
GROUP BY city
HAVING COUNT(order_id) > 100;

-- Find products whose average price is greater than 500.
SELECT product , AVG(price) 
FROM sales
GROUP BY product
HAVING AVG(price) > 500;

-- Find categories generating revenue greater than ₹1,00,000 
SELECT category , SUM(price * quantity) AS revenue
FROM sales
GROUP BY category
HAVING revenue > 100000;

-- Find customers whose total purchase is above the average purchase of all customers. 
						
SELECT customer_name , SUM(quantity * price ) FROM SALES 
GROUP  BY customer_name 
HAVING SUM(quantity * price ) >                     
( SELECT AVG(total_purchase) 
FROM                    
	(SELECT SUM(quantity * price ) AS total_purchase
	FROM sales
	GROUP BY customer_name ) AS customer_totals ) ;
    
-- Find cities whose total revenue is greater than the average revenue of all cities. 
SELECT city , SUM(quantity * price ) 
FROM sales
GROUP BY city
HAVING SUM(quantity * price ) > 
(SELECT AVG (total_revenue) FROM 
(SELECT SUM(quantity * price ) AS total_revenue
FROM sales 
GROUP BY city) AS city_totals);

/* For each city, show:

Number of Orders
Total Revenue
Average Revenue
Maximum Order Value
Minimum Order Value

in one query. */
SELECT city ,
 MAX( price * quantity ) AS Maximum_Order_Value,
 MIN(quantity * price ) AS Minimum_Order_Value,
 SUM(quantity * price ) AS Total_Revenue,
 AVG(quantity * price ) AS Average_Revenue,
 COUNT(order_id) AS Number_of_Orders
 FROM sales 
GROUP BY city;

-- Find customers who have placed more than 2 orders. 
SELECT customer_name FROM sales
GROUP BY customer_name
HAVING COUNT(order_id) > 2;

-- Find products that generated more than ₹1,00,000 in revenue.
SELECT product , SUM(price * quantity) AS revenue
FROM sales
GROUP BY product
HAVING SUM(price * quantity) > 100000;

-- Find cities where the average order value is greater than ₹30,000
SELECT city , AVG(price * quantity) as average_order_value
FROM sales
GROUP BY city
HAVING average_order_value > 30000;

-- Find categories having more than 5 orders
SELECT category , COUNT(order_id) AS orders
FROM sales
GROUP BY category 
HAVING COUNT(order_id) > 5;

-- Find customers whose minimum order value is greater than ₹10,000. 
SELECT customer_name , MIN(price * quantity) AS order_value
FROM sales
GROUP BY customer_name
HAVING MIN(price * quantity ) > 10000;

-- Find products sold in more than 2 cities.
SELECT product , COUNT(DISTINCT city) AS number_of_cities
FROM sales
GROUP BY product
HAVING number_of_cities > 2;

-- Find the top-selling category based on total quantity sold.
SELECT category , SUM(quantity) AS total_quantity
FROM sales
GROUP BY category
ORDER BY total_quantity DESC;

-- Find cities where the maximum order value exceeds ₹70,000.
SELECT city ,  MAX(quantity * price ) AS maximum_order_value
FROM sales
GROUP BY city
HAVING maximum_order_value > 70000;

-- Find products whose average selling price is below ₹2,000.
SELECT product , AVG(price)
FROM sales
GROUP BY product 
HAVING AVG(price) < 2000;

-- Find the customer(s) with the highest total revenue.
SELECT customer_name ,  SUM(quantity * price ) AS total_revenue
FROM sales
GROUP BY customer_name
ORDER BY total_revenue DESC
LIMIT 1;

-- Find the city with the lowest total revenue.
SELECT city , SUM(price * quantity) AS total_revenue
FROM sales
GROUP BY city
ORDER BY total_revenue
LIMIT 1;

-- Find products whose revenue is greater than the average product revenue.
SELECT product , SUM(quantity * price ) AS revenue 
FROM sales
GROUP BY product 
HAVING revenue > 
(SELECT AVG(total_revenue) 
FROM 
	(SELECT SUM(price * quantity ) AS total_revenue
	FROM sales 
	GROUP BY product) AS product_revenue);
    
-- Find customers whose total purchase is less than the average customer purchase.
SELECT customer_name , SUM(quantity * price ) total_purchase
FROM sales
GROUP BY customer_name
HAVING total_purchase < 
(SELECT AVG(customer_purchase)
FROM 
(SELECT  SUM(price * quantity) AS customer_purchase
FROM sales
GROUP BY customer_name) AS total_customer_purchase);

-- Find cities where total revenue is higher than Delhi's revenue.
SELECT city , SUM(price * quantity) AS total_revenue
FROM sales
GROUP BY city
HAVING total_revenue > 
(SELECT SUM(price * quantity ) AS Delhi_revenue
FROM sales
WHERE city = "Delhi"
GROUP BY city);

-- Find the category with the highest average order value.
SELECT category , AVG(price * quantity) 
FROM sales 
GROUP  BY category
ORDER BY category DESC 
LIMIT 1;

-- Find customers who spent more than the customer "Amit".
SELECT customer_name , SUM(price * quantity) as spend
FROM sales
GROUP BY customer_name
HAVING spend > (
SELECT SUM(price * quantity)
FROM sales
WHERE customer_name = "Amit");

-- Find the month having the highest total revenue.

SELECT MONTHNAME(order_date), SUM(price * quantity) AS total_revenue
FROM sales
GROUP BY MONTHNAME(order_date)
ORDER BY total_revenue DESC 
LIMIT 1;

-- Find products whose total quantity sold is above the average quantity sold per product.
SELECT product , SUM(quantity) AS total_quantity
FROM sales
GROUP BY product
HAVING total_quantity > 
						(SELECT AVG(sum_quantity) FROM
						(SELECT SUM(quantity) AS sum_quantity
                        FROM sales group by product) AS total_quantity);
                        
                        
-- Find cities contributing more than 30% of total revenue.
SELECT city , SUM(quantity * price ) 
FROM sales
GROUP BY city
HAVING SUM(quantity * price ) > 
(SELECT revenue * 0.3 FROM
(SELECT SUM(quantity * price ) AS revenue
FROM sales) AS total_revenue);

-- For every customer, show:

-- Total Orders
-- Total Revenue
-- Average Order Value
-- Highest Order
-- Lowest Order
SELECT customer_name ,
		COUNT(order_id) AS total_orders,
        SUM(price * quantity) AS total_revenue,
        AVG(price * quantity) AS average_order_value,
        MAX(price * quantity) AS highest_order,
        MIN(price * quantity) AS lowest_order
FROM sales
GROUP BY customer_name;


