use sales_analytics;

CREATE TABLE sales (
    order_id INT PRIMARY KEY,
    customer_name VARCHAR(100),
    city VARCHAR(50),
    product VARCHAR(100),
    category VARCHAR(50),
    quantity INT,
    price DECIMAL(10,2),
    order_date DATE
);
 
INSERT INTO sales
(order_id, customer_name, city, product, category, quantity, price, order_date)
VALUES
(101,'Dhruv','Delhi','Laptop','Electronics',1,65000,'2025-01-05'),
(102,'Amit','Mumbai','Mobile','Electronics',2,25000,'2025-01-08'),
(103,'Priya','Delhi','Headphones','Electronics',3,2000,'2025-01-12'),
(104,'Rahul','Bangalore','Chair','Furniture',4,3500,'2025-01-15'),
(105,'Sneha','Pune','Table','Furniture',1,8500,'2025-01-18'),
(106,'Ankit','Delhi','Laptop','Electronics',1,70000,'2025-02-02'),
(107,'Neha','Mumbai','Monitor','Electronics',2,15000,'2025-02-06'),
(108,'Riya','Pune','Chair','Furniture',6,3200,'2025-02-09'),
(109,'Vikas','Jaipur','Mobile','Electronics',1,28000,'2025-02-15'),
(110,'Karan','Delhi','Keyboard','Accessories',5,1200,'2025-02-18'),
(111,'Amit','Mumbai','Mouse','Accessories',8,700,'2025-03-02'),
(112,'Priya','Delhi','Laptop','Electronics',1,68000,'2025-03-06'),
(113,'Rahul','Bangalore','Desk','Furniture',2,12000,'2025-03-10'),
(114,'Sneha','Pune','Tablet','Electronics',2,18000,'2025-03-14'),
(115,'Dhruv','Delhi','Mobile','Electronics',1,30000,'2025-03-20'),
(116,'Neha','Mumbai','Chair','Furniture',3,3400,'2025-04-01'),
(117,'Ankit','Delhi','Monitor','Electronics',1,16000,'2025-04-05'),
(118,'Riya','Pune','Mouse','Accessories',10,650,'2025-04-09'),
(119,'Vikas','Jaipur','Keyboard','Accessories',6,1300,'2025-04-14'),
(120,'Karan','Delhi','Desk','Furniture',1,15000,'2025-04-18'),
(121,'Amit','Mumbai','Laptop','Electronics',1,72000,'2025-05-03'),
(122,'Priya','Delhi','Mobile','Electronics',2,29000,'2025-05-07'),
(123,'Rahul','Bangalore','Table','Furniture',2,9000,'2025-05-12'),
(124,'Sneha','Pune','Keyboard','Accessories',4,1100,'2025-05-18'),
(125,'Dhruv','Delhi','Headphones','Electronics',5,2500,'2025-05-22'),
(126,'Neha','Mumbai','Laptop','Electronics',1,69000,'2025-06-01'),
(127,'Ankit','Delhi','Chair','Furniture',2,3600,'2025-06-05'),
(128,'Riya','Pune','Monitor','Electronics',1,17000,'2025-06-10'),
(129,'Vikas','Jaipur','Tablet','Electronics',2,19000,'2025-06-14'),
(130,'Karan','Delhi','Mouse','Accessories',7,750,'2025-06-20');


select * from sales;

-- Count total orders from each city. -- 

SELECT city , COUNT(order_id) AS total_orders 
FROM sales GROUP BY city;

-- Find total revenue generated by each city. -- 
SELECT city , SUM(price * quantity) AS total_revenue 
FROM sales GROUP BY city;

-- Find average order value for every city. -- 
SELECT city , AVG(quantity * price) AS avg_order_value
FROM sales GROUP BY city ;

-- Show total quantity sold for each product. -- 
SELECT product , SUM(quantity) AS total_quantity
FROM sales GROUP BY product;

-- Find maximum price of each product. -- 
SELECT product , MAX(price) AS maximum_price
FROM sales GROUP BY product;

-- Find minimum price for each category. -- 
SELECT category , MIN(price) AS minimum_price
FROM sales GROUP BY category;

-- Find average quantity ordered for each product. -- 
SELECT product , AVG(quantity) AS average_quantity 
FROM sales GROUP BY product;

-- Show total revenue for every category. -- 
SELECT category , SUM(price * quantity) AS total_revenue
FROM sales GROUP  BY category;

-- Count unique customers in each city.--
SELECT city , COUNT(DISTINCT customer_name) AS unique_customer
FROM sales GROUP BY city;


-- Find the customer who placed the highest number of orders. -- 
SELECT customer_name , COUNT(order_id) AS total_orders
FROM sales GROUP BY customer_name
ORDER BY total_orders DESC
LIMIT 1;

-- Find total monthly revenue. -- 
SELECT MONTHNAME(order_date) , SUM(price * quantity ) AS monthly_revenue
FROM sales GROUP BY MONTHNAME(order_date);

-- Find the highest revenue city. -- 
SELECT MONTHNAME(order_date) , SUM(price * quantity ) AS monthly_revenue
FROM sales 
GROUP BY MONTHNAME(order_date)
ORDER BY monthly_revenue DESC
LIMIT 1;

-- Find the most ordered product. --
SELECT product , COUNT(quantity) FROM sales 
GROUP BY product
ORDER BY COUNT(quantity) DESC
LIMIT 1;

-- Find top 3 customers based on total purchase amount.
SELECT customer_name , SUM(quantity * price) AS purchase_amount
FROM sales
GROUP BY customer_name
ORDER BY purchase_amount DESC 
LIMIT 3;

-- Find cities having more than 100 orders. -- 
SELECT city , COUNT(order_id) AS total_orders 
FROM sales 
GROUP BY city
HAVING COUNT(order_id) > 100;

-- Find products whose average price is greater than 500.
SELECT product , AVG(price) 
FROM sales
GROUP BY product
HAVING AVG(price) > 500;

-- Find categories generating revenue greater than ₹1,00,000 
SELECT category , SUM(price * quantity) AS revenue
FROM sales
GROUP BY category
HAVING revenue > 100000;

