USE blinkitdb;

CREATE TABLE orders (
    order_id INT PRIMARY KEY,
    customer_id INT,
    customer_name VARCHAR(100),
    city VARCHAR(50),
    order_date DATE,
    category VARCHAR(50),
    product_name VARCHAR(100),
    quantity INT,
    price DECIMAL(10,2),
    payment_method VARCHAR(30),
    delivery_time INT,
    rating DECIMAL(2,1)
);

INSERT INTO orders VALUES
(1001,1,'Amit','Delhi','2025-01-03','Snacks','Chips',3,30,'UPI',18,4.5),
(1002,2,'Rohit','Mumbai','2025-01-05','Beverages','Coke',2,45,'Card',22,4.3),
(1003,3,'Neha','Delhi','2025-01-07','Dairy','Milk',5,60,'Cash',15,4.8),
(1004,4,'Priya','Bangalore','2025-01-08','Fruits','Apple',4,120,'UPI',19,4.6),
(1005,5,'Karan','Hyderabad','2025-01-09','Vegetables','Potato',8,35,'Card',24,4.1),
(1006,1,'Amit','Delhi','2025-02-02','Snacks','Biscuits',6,25,'UPI',17,4.4),
(1007,6,'Rahul','Mumbai','2025-02-05','Beverages','Pepsi',5,40,'Cash',20,4.0),
(1008,7,'Simran','Pune','2025-02-10','Personal Care','Shampoo',2,180,'UPI',23,4.9),
(1009,8,'Anjali','Delhi','2025-02-15','Dairy','Cheese',2,220,'Card',18,4.7),
(1010,9,'Mohit','Bangalore','2025-02-20','Bakery','Bread',3,45,'UPI',14,4.5),
(1011,10,'Sneha','Hyderabad','2025-03-03','Snacks','Namkeen',5,80,'Cash',19,4.3),
(1012,11,'Vikas','Delhi','2025-03-05','Frozen','Ice Cream',2,180,'Card',21,4.8),
(1013,12,'Pooja','Mumbai','2025-03-07','Beverages','Juice',4,90,'UPI',20,4.6),
(1014,2,'Rohit','Mumbai','2025-03-09','Household','Detergent',2,260,'Card',26,4.2),
(1015,3,'Neha','Delhi','2025-03-12','Fruits','Banana',12,10,'Cash',16,4.9),
(1016,5,'Karan','Hyderabad','2025-04-01','Vegetables','Tomato',6,40,'UPI',18,4.4),
(1017,13,'Arjun','Pune','2025-04-05','Bakery','Cake',1,350,'Card',24,4.8),
(1018,14,'Nisha','Delhi','2025-04-09','Dairy','Butter',2,210,'UPI',19,4.7),
(1019,6,'Rahul','Mumbai','2025-04-13','Snacks','Cookies',3,90,'Cash',22,4.1),
(1020,15,'Ritu','Bangalore','2025-04-17','Beverages','Coffee',1,420,'Card',20,4.9),
(1021,16,'Ajay','Delhi','2025-05-02','Personal Care','Soap',6,55,'UPI',17,4.4),
(1022,17,'Meena','Pune','2025-05-06','Vegetables','Onion',10,28,'Cash',15,4.2),
(1023,18,'Aakash','Mumbai','2025-05-08','Frozen','Pizza',2,320,'Card',23,4.8),
(1024,19,'Kriti','Delhi','2025-05-10','Bakery','Cookies',5,95,'UPI',16,4.6),
(1025,20,'Dev','Hyderabad','2025-05-12','Fruits','Orange',4,110,'Cash',18,4.3),
(1026,7,'Simran','Pune','2025-06-03','Household','Cleaner',2,260,'UPI',22,4.5),
(1027,8,'Anjali','Delhi','2025-06-06','Dairy','Paneer',3,150,'Card',17,4.9),
(1028,9,'Mohit','Bangalore','2025-06-08','Snacks','Chips',10,30,'Cash',15,4.4),
(1029,10,'Sneha','Hyderabad','2025-06-11','Beverages','Tea',2,260,'UPI',20,4.7),
(1030,11,'Vikas','Delhi','2025-06-14','Personal Care','Face Wash',1,350,'Card',21,4.8);



-- ========================================
-- Blinkit Sales Analysis using SQL
-- ========================================


-- Calculate total revenue generated by Blinkit.
SELECT SUM(price * quantity) AS Total_revenue 
FROM orders;

-- Find total number of orders.
SELECT SUM(order_id) FROM orders;

-- Find total unique customers.
SELECT SUM(DISTINCT customer_id) FROM orders;

-- Calculate average order value.
SELECT AVG(price * quantity) FROM orders ;

-- Find top 10 highest spending customers.
SELECT customer_id  , SUM(price * quantity ) 
FROM orders 
GROUP BY customer_id 
ORDER BY SUM(price * quantity) DESC
LIMIT 10 ;

-- Find total revenue generated by each city. 
SELECT city , SUM(price * quantity ) AS Total_revenue 
FROM orders 
GROUP BY city ;

-- Find total revenue by product category.
SELECT Category , SUM(price * quantity ) AS Total_revenue 
FROM orders 
GROUP BY Category ;

-- Find total quantity sold for every product.
SELECT product_name , SUM(quantity) AS Total_quantity
FROM orders 
GROUP BY product_name;

-- Find monthly revenue.
SELECT MONTHNAME(order_date) AS Months , SUM(price * quantity ) AS Revenue
FROM orders 
GROUP BY MONTHNAME(order_date) ;

-- Identify the Highest Revenue Month
SELECT  MONTHNAME(order_date) AS Month , SUM(price * quantity ) AS Revenue  
FROM orders 
GROUP BY MONTHNAME(order_date)
ORDER BY Revenue DESC 
LIMIT 1;

-- Find top 5 selling products based on quantity.
SELECT product_name , SUM(quantity) AS Quantity
FROM orders 
GROUP BY product_name 
ORDER BY SUM(quantity) DESC
LIMIT 5;

-- Find top 5 products generating highest revenue.
SELECT product_name , SUM(quantity * price ) AS revenue 
FROM orders 
GROUP BY product_name 
ORDER BY SUM(quantity * price ) DESC 
LIMIT 5;

-- Calculate average delivery time for each city.
SELECT city , AVG(delivery_time) AS Avg_delivery_time 
FROM orders 
GROUP BY city ;

-- Find cities where average delivery time exceeds 20 minutes.
SELECT city , AVG(delivery_time) AS Avg_delivery_time 
FROM orders 
GROUP BY city 
HAVING Avg_delivery_time > 20;

-- Find customer lifetime value (Total Revenue per Customer). 
SELECT customer_id , SUM(price * quantity) AS Total_Revenue_per_Customer
FROM orders 
GROUP BY customer_id ;

-- Segment customers based on total spending.
-- Example
-- Premium (> ₹1500)
-- Gold (₹1000–1500)
-- Silver (₹500–999)
-- Regular (< ₹500)
SELECT
    customer_id,
    SUM(quantity * price) AS total_spending,
    CASE
        WHEN SUM(quantity * price) > 1500 THEN 'Premium'
        WHEN SUM(quantity * price) BETWEEN 1000 AND 1500 THEN 'Gold'
        WHEN SUM(quantity * price) BETWEEN 500 AND 999 THEN 'Silver'
        ELSE 'Regular'
    END AS customer_segment
FROM orders
GROUP BY customer_id ; 

-- Find repeat customers (placed more than one order).
SELECT customer_id  FROM orders 
GROUP BY customer_id 
HAVING COUNT(order_id) > 1;

-- Find customers whose spending is above the average customer spending.
SELECT customer_id , SUM(price * quantity ) AS Customer_spending 
FROM orders 
GROUP BY customer_id 
HAVING SUM(price * quantity ) > 
( 
SELECT AVG(customer_spending) FROM 
( SELECT SUM(price * quantity ) AS customer_spending
FROM orders
GROUP BY customer_id ) AS customer_spending_table ) ; 


