-- =====================================================
-- Day 34 — Interview SQL Challenge
-- Difficulty: Easy → Medium → Hard
-- Total Questions: 25
-- Topics Covered:
-- 1. SELECT
-- 2. WHERE
-- 3. GROUP BY
-- 4. HAVING
-- 5. ORDER BY
-- =====================================================


-- =====================================================
-- Database Setup
-- =====================================================

CREATE DATABASE interview_sql_db;

USE interview_sql_db;

CREATE TABLE sales (
    order_id INT PRIMARY KEY,
    customer_name VARCHAR(50),
    city VARCHAR(50),
    category VARCHAR(50),
    product VARCHAR(50),
    quantity INT,
    price DECIMAL(10,2),
    order_date DATE
);

INSERT INTO sales
(order_id, customer_name, city, category, product, quantity, price, order_date)
VALUES
(101,'Amit','Delhi','Electronics','Laptop',1,55000,'2024-01-05'),
(102,'Priya','Mumbai','Furniture','Chair',4,2500,'2024-01-06'),
(103,'Rahul','Delhi','Electronics','Mouse',5,600,'2024-01-08'),
(104,'Sneha','Pune','Clothing','Jacket',2,1800,'2024-01-10'),
(105,'Rohan','Mumbai','Electronics','Keyboard',3,1200,'2024-01-11'),
(106,'Anjali','Delhi','Furniture','Table',1,7000,'2024-01-13'),
(107,'Karan','Jaipur','Clothing','T-Shirt',6,700,'2024-01-15'),
(108,'Neha','Pune','Electronics','Monitor',2,15000,'2024-01-18'),
(109,'Vikas','Delhi','Furniture','Sofa',1,25000,'2024-01-20'),
(110,'Pooja','Mumbai','Clothing','Jeans',4,1500,'2024-01-22'),
(111,'Ritu','Delhi','Electronics','Laptop',1,62000,'2024-01-25'),
(112,'Arjun','Jaipur','Furniture','Bed',1,30000,'2024-01-27'),
(113,'Simran','Pune','Electronics','Headphones',3,2500,'2024-02-01'),
(114,'Manish','Delhi','Clothing','Shoes',2,3500,'2024-02-04'),
(115,'Meera','Mumbai','Furniture','Cupboard',1,18000,'2024-02-06'),
(116,'Akash','Delhi','Electronics','Printer',2,8500,'2024-02-08'),
(117,'Nisha','Pune','Clothing','Sweater',3,1200,'2024-02-10'),
(118,'Deepak','Jaipur','Electronics','Tablet',2,22000,'2024-02-12'),
(119,'Sonal','Mumbai','Furniture','Desk',2,9000,'2024-02-14'),
(120,'Varun','Delhi','Electronics','Camera',1,45000,'2024-02-15'),
(121,'Kavita','Pune','Furniture','Chair',5,2500,'2024-02-17'),
(122,'Mohit','Delhi','Clothing','Shirt',4,1000,'2024-02-19'),
(123,'Riya','Mumbai','Electronics','Laptop',2,58000,'2024-02-22'),
(124,'Aditya','Jaipur','Furniture','Dining Table',1,22000,'2024-02-24'),
(125,'Isha','Delhi','Electronics','Smartphone',3,28000,'2024-02-25');

-- =====================================================
-- Easy Questions (1–10)
-- =====================================================

-- Display all columns from the sales table.
SELECT * FROM sales ;

-- Show only customer_name and city.
SELECT customer_name , city FROM sales ;

-- Find orders where city = 'Delhi'.
SELECT * FROM sales 
WHERE city = "Delhi";

-- Find products with price > 500.
SELECT product , price FROM sales 
WHERE price > 500;

-- Find orders where quantity >= 5 
SELECT * FROM sales 
WHERE quantity >= 5;

-- Show unique categories.
SELECT DISTINCT category FROM sales ;

-- Sort products by price in ascending order.
SELECT product , price 
FROM sales 
ORDER BY price ASC;

-- Sort products by price in descending order.
SELECT product , price 
FROM sales 
ORDER BY price DESC;

-- Display the first 5 rows. 
SELECT * FROM sales 
LIMIT 5;

-- Find orders placed after '2024-01-01'. 
SELECT * FROM sales 
WHERE order_date > '2024-01-01';

-- ==========================================
-- Medium Questions
-- ==========================================

-- Calculate total revenue for each row (quantity * price). 
SELECT quantity * price AS Total_revenue FROM sales;

-- Find total quantity sold per category. 
SELECT category , SUM(quantity ) AS Total_quantity FROM sales 
GROUP BY category;

-- Find average price per category.
SELECT category , AVG(price) FROM sales 
GROUP BY category ;

-- Count orders in each city.
SELECT city , COUNT(order_id) AS Number_of_orders FROM sales  
GROUP BY city;

-- Find total revenue generated by each city.
SELECT city , SUM(quantity * price ) AS Total_revenue 
FROM sales 
GROUP BY city ;

-- Display cities having more than 3 orders.
SELECT city , COUNT(order_id) AS Orders 
FROM sales 
GROUP BY city 
HAVING Orders > 3;

-- Find categories with average price greater than 1000.
SELECT category , AVG(price) AS Avg_price 
FROM sales 
GROUP BY category 
HAVING Avg_price > 1000;

-- Find the top 3 most expensive products.
SELECT product , price 
FROM sales 
ORDER BY price DESC 
LIMIT 3;

-- Find the total number of unique customers.
SELECT COUNT(DISTINCT customer_name) AS total_number_of_unique_customer
FROM sales ;

-- Find the category with the highest total quantity sold.
SELECT category , SUM(quantity ) AS total_quantity_sold
FROM sales 
GROUP BY category
ORDER BY SUM(quantity) DESC 
LIMIT 1;

-- =====================================================
-- Hard Questions (21–25)
-- =====================================================

--  Find cities where total revenue is greater than 10, 000 
SELECT city ,SUM(quantity * price ) AS total_revenue 
FROM sales 
GROUP BY city 
HAVING total_revenue > 10000;

-- Find the second highest priced product.
SELECT product , price 
FROM sales 
ORDER BY price DESC
LIMIT 1 OFFSET 1;

-- Find categories contributing more than 30% of total revenue. 
SELECT category , SUM(quantity * price ) AS total_revenue 
FROM sales 
GROUP BY category
HAVING SUM(quantity * price ) > ( 
									SELECT SUM(quantity * price) * 0.30 
                                    FROM sales 
								) ;
                                
-- Find the city with the highest average order value.
SELECT city,
       AVG(quantity * price) AS avg_order_value
FROM sales
GROUP BY city
ORDER BY avg_order_value DESC
LIMIT 1;


-- Find the category whose total revenue is above the overall average category revenue.
SELECT category , SUM(quantity * price) AS total_revenue 
FROM sales 
GROUP BY category 
HAVING SUM(quantity * price) > 
	(
    SELECT AVG(category_revenue) AS Avg_category_revenue
	FROM 
		( SELECT SUM(quantity * price) AS category_revenue 
		FROM sales 
		GROUP BY category ) AS category_revenue_table 
	) ; 
